# Generated by Django 5.2.5 on 2025-09-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cal_in_grams', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cal_in_portion', models.DecimalField(decimal_places=2, default=None, max_digits=6)),
            ],
        ),
    ]
