# Generated by Django 5.2.5 on 2025-09-14 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cal_in_grams',
        ),
        migrations.AddField(
            model_name='item',
            name='cal_in_gram',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EatenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.DecimalField(decimal_places=2, default=None, max_digits=6)),
                ('grams', models.DecimalField(decimal_places=2, default=None, max_digits=6)),
                ('date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
