# Generated by Django 5.2.5 on 2025-09-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_cal_in_grams_item_cal_in_gram_eatenitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cal_in_gram',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=6),
        ),
    ]
