# Generated by Django 5.2.5 on 2025-09-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_cal_in_gram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cal_in_gram',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=6),
        ),
        migrations.AlterField(
            model_name='item',
            name='cal_in_portion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6),
        ),
    ]
