# Generated by Django 5.2.5 on 2025-09-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_cal_in_gram_alter_item_cal_in_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cal_in_gram',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cal_in_portion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
