# Generated by Django 5.2.5 on 2025-09-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_eatenitem_grams_alter_eatenitem_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatenitem',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
    ]
